-- something in db
-- changeset Aman:1737108894555-1
CREATE TABLE "user_table" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" VARCHAR(500),
    "password" VARCHAR(500),
    "verification_code" VARCHAR(10),
    "is_verified" BOOLEAN DEFAULT FALSE,
    CONSTRAINT "user_table_pkey" PRIMARY KEY ("id")
);

-- changeset Aman:1737108894555-2
CREATE TABLE "employee" ("id" INTEGER NOT NULL ,CONSTRAINT "employee_pkey" PRIMARY KEY ("id"));

-- changeset Aman:1737108894555-3
CREATE TABLE "student" ("id" INTEGER NOT NULL,CONSTRAINT "student_pkey" PRIMARY KEY ("id"));

-- changeset AYUSH:1737108894547-6
CREATE TABLE "admin" ("id" INTEGER NOT NULL, CONSTRAINT "admin_pkey" PRIMARY KEY ("id"));
-- changeset AYUSH:1737108894547-8
ALTER TABLE "student" ADD CONSTRAINT "fk4bfhdr4y6nbfppbxyl8v3a174" FOREIGN KEY ("id") REFERENCES "user_table" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset AYUSH:1737108894547-9
ALTER TABLE "admin" ADD CONSTRAINT "fk54o4fghe5haybdn7456s7voy6" FOREIGN KEY ("id") REFERENCES "user_table" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset AYUSH:1737108894547-10
ALTER TABLE "employee" ADD CONSTRAINT "fkrs9p6wnc5mqn645ivnt089wc8" FOREIGN KEY ("id") REFERENCES "user_table" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;


-- changeset Aman:1737108894555-11
CREATE TABLE Role (
    id SERIAL PRIMARY KEY,
    role VARCHAR(255) NOT NULL
);

-- changeset Aman:1737108894555-11
CREATE TABLE "user_roles" (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES "user_table" ("id") ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES "role" ("id") ON DELETE CASCADE
);



